# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# +---------------------------------------------------------+ #
# |       Friend System by Despical (Version 1.0.0)         | #
# +---------------------------------------------------------+ #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Enable this option when you're using MySQL, otherwise it won't work.
# Be careful when changing this because there is NO migrator between
# flat file and MySQL for player stats.
DatabaseActivated: false

Update-Notifier:
  # Should we check for updates on plugin start/after admin join?
  Enabled: true
  # Should we inform you when beta version is out?
  # Also note that BETA IS NOT ALWAYS AS STABLE AS NORMAL RELEASE!
  Notify-Beta-Versions: true

# Don't edit it. But who's stopping you? It's your server!
File-Version: 0

# No way! You've reached the end! But... where's the dragon!?